#! /usr/bin/env python

"""Convert a DSV file to CSV.
"""

import sys
import argparse
import csv
import dsv

def main(options):
    """Main program."""
    csv.writer(sys.stdout).writerows(
        csv.reader(sys.stdin, dialect=dsv.DSVDialect)
    )
    return

def get_options():
    """Get options for the script."""
    parser = argparse.ArgumentParser(
               description="convert DSV data on stdin to CSV on stdout",
             )
    # parser.add_argument() calls here
    options = parser.parse_args()
    # extra processing of options here
    return options

if __name__ == "__main__":
    main(get_options())
